-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-09-13 16:44:50 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c


--Group: A06_Group126
--Group members: Md Rahman, Yamini Vaka, Ye Chen

--Capture run of script in file called pf_schema_output.txt 

SPOOL pf_schema_output.txt


DROP TABLE clinic CASCADE CONSTRAINTS;

DROP TABLE drug CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE participant CASCADE CONSTRAINTS;

DROP TABLE pet CASCADE CONSTRAINTS;

DROP TABLE pet_type CASCADE CONSTRAINTS;

DROP TABLE prescription CASCADE CONSTRAINTS;

DROP TABLE service CASCADE CONSTRAINTS;

DROP TABLE specialisation CASCADE CONSTRAINTS;

DROP TABLE training CASCADE CONSTRAINTS;

DROP TABLE vet CASCADE CONSTRAINTS;

DROP TABLE visit CASCADE CONSTRAINTS;

DROP TABLE visit_service CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE clinic (
    cli_id       NUMBER(7) NOT NULL,
    cli_name     VARCHAR2(40) NOT NULL,
    cli_address  VARCHAR2(50) NOT NULL,
    cli_phonenum NUMBER(10) NOT NULL,
    vet_id       NUMBER(7) NOT NULL
);

COMMENT ON COLUMN clinic.cli_id IS
    'clinic ID';

COMMENT ON COLUMN clinic.cli_name IS
    'clinic name';

COMMENT ON COLUMN clinic.cli_address IS
    'clinic address';

COMMENT ON COLUMN clinic.cli_phonenum IS
    'clinic phone number';

COMMENT ON COLUMN clinic.vet_id IS
    'veterinary ID';

CREATE UNIQUE INDEX clinic__idx ON
    clinic (
        vet_id
    ASC );

ALTER TABLE clinic ADD CONSTRAINT clinic_pk PRIMARY KEY ( cli_id );

CREATE TABLE drug (
    drug_id                NUMBER(7) NOT NULL,
    drug_name              VARCHAR2(20) NOT NULL,
    drug_usage_instruction VARCHAR2(30) NOT NULL,
    drug_standard_cost     NUMBER(7, 2) NOT NULL
);

COMMENT ON COLUMN drug.drug_id IS
    'drug ID';

COMMENT ON COLUMN drug.drug_name IS
    'drug name';

COMMENT ON COLUMN drug.drug_usage_instruction IS
    'drug usage instruction';

COMMENT ON COLUMN drug.drug_standard_cost IS
    'drug standard cost';

ALTER TABLE drug ADD CONSTRAINT drug_pk PRIMARY KEY ( drug_id );

CREATE TABLE owner (
    owner_id       NUMBER(7) NOT NULL,
    owner_gname    VARCHAR2(20) NOT NULL,
    owner_fname    VARCHAR2(20) NOT NULL,
    owner_phonenum CHAR(10) NOT NULL
);

COMMENT ON COLUMN owner.owner_id IS
    'owner id';

COMMENT ON COLUMN owner.owner_gname IS
    'owner given name';

COMMENT ON COLUMN owner.owner_fname IS
    'owner first name';

COMMENT ON COLUMN owner.owner_phonenum IS
    'owner phone number';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE participant (
    train_id          NUMBER(7) NOT NULL,
    vet_id            NUMBER(7) NOT NULL,
    par_vet_completed CHAR(1) NOT NULL,
    par_vet_expiry    DATE
);

ALTER TABLE participant
    ADD CONSTRAINT chk_complete CHECK ( par_vet_completed IN ( 'N', 'Y' ) );

COMMENT ON COLUMN participant.train_id IS
    'training ID(surrogate key)';

COMMENT ON COLUMN participant.vet_id IS
    'veterinary ID';

COMMENT ON COLUMN participant.par_vet_completed IS
    'participants completed the training, Y-Yes, N-No';

COMMENT ON COLUMN participant.par_vet_expiry IS
    'training expiry for participants ';

ALTER TABLE participant ADD CONSTRAINT participant_pk PRIMARY KEY ( train_id,
                                                                    vet_id );

CREATE TABLE pet (
    pet_id         NUMBER(7) NOT NULL,
    pet_name       VARCHAR2(10) NOT NULL,
    pet_birth_year DATE NOT NULL,
    pet_deceased   CHAR(1),
    pet_type_code  NUMBER(5) NOT NULL,
    owner_id       NUMBER(7) NOT NULL
);

ALTER TABLE pet
    ADD CONSTRAINT chk_pet_deceased CHECK ( pet_deceased IN ( 'A', 'D' ) );

COMMENT ON COLUMN pet.pet_id IS
    'pet id (Note: pet need to have at least one visit, otherwise pet can''t be record)'
    ;

COMMENT ON COLUMN pet.pet_name IS
    'pet name';

COMMENT ON COLUMN pet.pet_birth_year IS
    'pet year of birth';

COMMENT ON COLUMN pet.pet_deceased IS
    'pet deceased(D-deceased, A-alive)';

COMMENT ON COLUMN pet.pet_type_code IS
    'pet type code';

COMMENT ON COLUMN pet.owner_id IS
    'owner id';

ALTER TABLE pet ADD CONSTRAINT pet_pk PRIMARY KEY ( pet_id );

CREATE TABLE pet_type (
    pet_type_code NUMBER(5) NOT NULL,
    pet_type_name VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN pet_type.pet_type_code IS
    'pet type code';

COMMENT ON COLUMN pet_type.pet_type_name IS
    'pet type name';

ALTER TABLE pet_type ADD CONSTRAINT pet_type_pk PRIMARY KEY ( pet_type_code );

CREATE TABLE prescription (
    pres_id        NUMBER(10) NOT NULL,
    drug_id        NUMBER(7) NOT NULL,
    visit_id       NUMBER(10) NOT NULL,
    pres_dose      CHAR(10) NOT NULL,
    pres_frequency CHAR(20) NOT NULL,
    pres_drug_qty  NUMBER(3) NOT NULL,
    pres_drug_cost NUMBER(6, 2) NOT NULL
);

COMMENT ON COLUMN prescription.pres_id IS
    'prescription ID (surrogate key)';

COMMENT ON COLUMN prescription.drug_id IS
    'drug ID';

COMMENT ON COLUMN prescription.visit_id IS
    'visit ID(surrogate key)';

COMMENT ON COLUMN prescription.pres_dose IS
    'prescription dose';

COMMENT ON COLUMN prescription.pres_frequency IS
    'prescription frequency';

COMMENT ON COLUMN prescription.pres_drug_cost IS
    'prescription drug cost';

ALTER TABLE prescription ADD CONSTRAINT prescription_pk PRIMARY KEY ( pres_id );

ALTER TABLE prescription ADD CONSTRAINT prescription_nk UNIQUE ( visit_id,
                                                                 drug_id );

CREATE TABLE service (
    serivce_code          CHAR(5) NOT NULL,
    service_desc          VARCHAR2(80) NOT NULL,
    service_standard_cost NUMBER(8, 2) NOT NULL
);

COMMENT ON COLUMN service.serivce_code IS
    'service code';

COMMENT ON COLUMN service.service_desc IS
    'service description';

COMMENT ON COLUMN service.service_standard_cost IS
    'service standard cost';

ALTER TABLE service ADD CONSTRAINT service_pk PRIMARY KEY ( serivce_code );

CREATE TABLE specialisation (
    spec_code NUMBER(5) NOT NULL,
    spec_name VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN specialisation.spec_code IS
    'specialisation code';

COMMENT ON COLUMN specialisation.spec_name IS
    'specialisation name';

ALTER TABLE specialisation ADD CONSTRAINT specialisation_pk PRIMARY KEY ( spec_code )
;

CREATE TABLE training (
    train_id       NUMBER(7) NOT NULL,
    train_datetime DATE NOT NULL,
    train_name     VARCHAR2(50) NOT NULL,
    train_duration CHAR(10) NOT NULL,
    vet_id         NUMBER(7) NOT NULL,
    cli_id         NUMBER(7) NOT NULL
);

COMMENT ON COLUMN training.train_id IS
    'training ID(surrogate key)';

COMMENT ON COLUMN training.train_datetime IS
    'training date time';

COMMENT ON COLUMN training.train_name IS
    'training name';

COMMENT ON COLUMN training.train_duration IS
    'training duration';

COMMENT ON COLUMN training.vet_id IS
    'veterinary ID';

COMMENT ON COLUMN training.cli_id IS
    'clinic ID';

ALTER TABLE training ADD CONSTRAINT training_pk PRIMARY KEY ( train_id );

ALTER TABLE training ADD CONSTRAINT training_nk UNIQUE ( vet_id,
                                                         cli_id );

CREATE TABLE vet (
    vet_id       NUMBER(7) NOT NULL,
    vet_gname    VARCHAR2(20),
    vet_fname    VARCHAR2(20) NOT NULL,
    vet_phonenum CHAR(10) NOT NULL,
    vet_empdate  DATE NOT NULL,
    spec_code    NUMBER(5),
    cli_id       NUMBER(7) NOT NULL
);

COMMENT ON COLUMN vet.vet_id IS
    'veterinary ID';

COMMENT ON COLUMN vet.vet_gname IS
    'veterinary given name';

COMMENT ON COLUMN vet.vet_fname IS
    'veterinary first name';

COMMENT ON COLUMN vet.vet_phonenum IS
    'veterinary phone number';

COMMENT ON COLUMN vet.vet_empdate IS
    'veterinary employment date';

COMMENT ON COLUMN vet.spec_code IS
    'specialisation code';

COMMENT ON COLUMN vet.cli_id IS
    'clinic ID';

ALTER TABLE vet ADD CONSTRAINT vet_pk PRIMARY KEY ( vet_id );

CREATE TABLE visit (
    visit_id             NUMBER(10) NOT NULL,
    vet_id               NUMBER(7) NOT NULL,
    visit_datetime       DATE NOT NULL,
    visit_pet_weight     NUMBER(5, 2) NOT NULL,
    visit_length         CHAR(7) NOT NULL,
    visit_notes          VARCHAR2(50),
    visit_payment_method CHAR(4) NOT NULL,
    visit_payment_total  NUMBER(7, 2) NOT NULL,
    cli_id               NUMBER(7) NOT NULL,
    pet_id               NUMBER(7) NOT NULL,
    visit_prev_id        NUMBER(10)
);

ALTER TABLE visit
    ADD CONSTRAINT chk_payment_method CHECK ( visit_payment_method IN ( 'CASH', 'EFT'
    ) );

COMMENT ON COLUMN visit.visit_id IS
    'visit ID(surrogate key)';

COMMENT ON COLUMN visit.vet_id IS
    'veterinary ID';

COMMENT ON COLUMN visit.visit_datetime IS
    'visit date and time';

COMMENT ON COLUMN visit.visit_pet_weight IS
    'visit pet''s weight(like: 52.35)';

COMMENT ON COLUMN visit.visit_length IS
    'visit time length(like: 5 hrs)';

COMMENT ON COLUMN visit.visit_notes IS
    'notes during the visit time';

COMMENT ON COLUMN visit.visit_payment_method IS
    'payment method(CASH-use cash to pay or EFT-use eftpos to pay)';

COMMENT ON COLUMN visit.visit_payment_total IS
    'visit payment total amount';

COMMENT ON COLUMN visit.cli_id IS
    'clinic ID';

COMMENT ON COLUMN visit.pet_id IS
    'pet id (Note: pet need to have at least one visit, otherwise pet can''t be record)'
    ;

COMMENT ON COLUMN visit.visit_prev_id IS
    'visit ID(surrogate key)';

ALTER TABLE visit ADD CONSTRAINT visit_pk PRIMARY KEY ( visit_id );

ALTER TABLE visit ADD CONSTRAINT visit_nk UNIQUE ( visit_datetime,
                                                   vet_id );

CREATE TABLE visit_service (
    visit_id           NUMBER(10) NOT NULL,
    serivce_code       CHAR(5) NOT NULL,
    visit_service_cost NUMBER(8, 2) NOT NULL
);

COMMENT ON COLUMN visit_service.visit_id IS
    'visit ID(surrogate key)';

COMMENT ON COLUMN visit_service.serivce_code IS
    'service code';

COMMENT ON COLUMN visit_service.visit_service_cost IS
    'visit service cost';

ALTER TABLE visit_service ADD CONSTRAINT visit_service_pk PRIMARY KEY ( serivce_code,
                                                                        visit_id );

ALTER TABLE training
    ADD CONSTRAINT clinic_training FOREIGN KEY ( cli_id )
        REFERENCES clinic ( cli_id );

ALTER TABLE vet
    ADD CONSTRAINT clinic_vet FOREIGN KEY ( cli_id )
        REFERENCES clinic ( cli_id );

ALTER TABLE visit
    ADD CONSTRAINT clinic_visit FOREIGN KEY ( cli_id )
        REFERENCES clinic ( cli_id );

ALTER TABLE prescription
    ADD CONSTRAINT drug_prescription FOREIGN KEY ( drug_id )
        REFERENCES drug ( drug_id );

ALTER TABLE pet
    ADD CONSTRAINT owner_pet FOREIGN KEY ( owner_id )
        REFERENCES owner ( owner_id );

ALTER TABLE pet
    ADD CONSTRAINT pet_pet_type FOREIGN KEY ( pet_type_code )
        REFERENCES pet_type ( pet_type_code );

ALTER TABLE visit
    ADD CONSTRAINT pet_visit FOREIGN KEY ( pet_id )
        REFERENCES pet ( pet_id );

ALTER TABLE visit_service
    ADD CONSTRAINT service_visit_service FOREIGN KEY ( serivce_code )
        REFERENCES service ( serivce_code );

ALTER TABLE participant
    ADD CONSTRAINT training_participant FOREIGN KEY ( train_id )
        REFERENCES training ( train_id );

ALTER TABLE clinic
    ADD CONSTRAINT vet_clinic FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE participant
    ADD CONSTRAINT vet_participant FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE vet
    ADD CONSTRAINT vet_specialisation FOREIGN KEY ( spec_code )
        REFERENCES specialisation ( spec_code );

ALTER TABLE training
    ADD CONSTRAINT vet_training FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE visit
    ADD CONSTRAINT vet_visit FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE prescription
    ADD CONSTRAINT visit_prescription FOREIGN KEY ( visit_id )
        REFERENCES visit ( visit_id );

ALTER TABLE visit
    ADD CONSTRAINT visit_prev FOREIGN KEY ( visit_prev_id )
        REFERENCES visit ( visit_id );

ALTER TABLE visit_service
    ADD CONSTRAINT visit_visit_service FOREIGN KEY ( visit_id )
        REFERENCES visit ( visit_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             1
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0



SPOOL off